#!/bin/bash

RISE_DIR=$(pwd)
LABEL=$(date +"%Y-%m-%d-%H%M%S")
IPADDR=`hostname -I | cut -d ' ' -f1`

# LABEL is autogenerated for current date and time
# packets are downloaded to and stored in the label directory
# start LogReader through websocket on port 8080
cd $RISE_DIR/scripts/websocketd
./websocketd --port=8080 python $RISE_DIR/scripts/LogReader/LogReader.py -d $RISE_DIR/packets/$LABEL &
#./websocketd --port=8080 --address="$IPADDR" python $RISE_DIR/scripts/LogReader/LogReader.py -d $RISE_DIR/$LABEL &

# tell PostReceiver which directory to save into
echo "<?php \$PacketsPath=\"$RISE_DIR/packets/$LABEL/\"; ?>" > $RISE_DIR/PostReceiver/logfile.php


# also start PacketSender to send fake packets,
# if testing without iridium transmitting.
#cd $RISE_DIR/scripts/PacketSender
#./PacketSender.py &
# ./PacketSender.sh

# start PacketDownloader
#cd $RISE_DIR/scripts/PacketDownloader
#./PacketDownloader.py -l $LABEL -d $RISE_DIR &
#./fakePacketDownloader.py -d $RISE_DIR/$LABEL &
